#!/bin/bash

# Install base packages
pacman -Sy git base base-devel gcc python cmake networkmanager sudo

# Set hostname
echo "dzordzu" > /etc/hostname

# Set hosts
echo "127.0.0.1   localhost" >> /etc/hosts
echo "::1   localhost" >> /etc/hosts
echo "127.0.1.1   dzordzu.localdomain dzordzu" >> /etc/hosts

# Install trizen
git clone https://aur.archlinux.org/trizen.git
cd trizen
makepkg -si
rm -rf ./trizen

# Create user
# useradd 

# Install other packages
trizen -Sy \
  bluez \
  expac \
  xorg \
  xorg-server \
  xorg-xinit \
  plasma \
  sdm \
  kcalc \
  ktexteditor \
  kate \
  kwin \
  grub \
  grub-customizer \
  vim \
  vim-instant-markdown \
  zsh \
  oh-my-zsh \
  mps-youtube \
  mpv \
  docker \
  docker-compose \
  bitwarden \
  antibody \
  openssh \
  curl \
  wget \
  jq \
  zip \
  gzip \
  nodejs \
  firefox \
  tor \
  torsocks \
  thunderbird \
  telegram-desktop
  
# Config mpsyt
mpsyt "set player mpv" &
mpsyt "set search_music false" &
kill -9 $(pgrep -x mpsyt)

